//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeWork.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;customers&gt;
        ///  &lt;customer&gt;
        ///    &lt;id&gt;ALFKI&lt;/id&gt;
        ///    &lt;name&gt;Alfreds Futterkiste&lt;/name&gt;
        ///    &lt;address&gt;Obere Str. 57&lt;/address&gt;
        ///    &lt;city&gt;Berlin&lt;/city&gt;
        ///    &lt;postalcode&gt;12209&lt;/postalcode&gt;
        ///    &lt;country&gt;Germany&lt;/country&gt;
        ///    &lt;phone&gt;030-0074321&lt;/phone&gt;
        ///    &lt;fax&gt;030-0076545&lt;/fax&gt;
        ///    &lt;orders&gt;
        ///      &lt;order&gt;
        ///        &lt;id&gt;10643&lt;/id&gt;
        ///        &lt;orderdate&gt;1997-08-25T00:00:00&lt;/orderdate&gt;
        ///        &lt;total&gt;814.50&lt;/total&gt;
        ///      &lt;/order&gt;
        ///      &lt;order&gt;
        ///        &lt;id&gt;10692&lt;/id&gt;
        ///        &lt;orderdate&gt;199 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
    }
}
